package sdl

/*
#include "gosdl.h"
*/
import "C"

type SysWMType C.SDL_SYSWM_TYPE

const (
	SYSWM_UNKNOWN  SysWMType = C.SDL_SYSWM_UNKNOWN
	SYSWM_WINDOWS  SysWMType = C.SDL_SYSWM_WINDOWS
	SYSWM_X11      SysWMType = C.SDL_SYSWM_X11
	SYSWM_DIRECTFB SysWMType = C.SDL_SYSWM_DIRECTFB
	SYSWM_COCOA    SysWMType = C.SDL_SYSWM_COCOA
	SYSWM_UIKIT    SysWMType = C.SDL_SYSWM_UIKIT
	SYSWM_WAYLAND  SysWMType = C.SDL_SYSWM_WAYLAND
	SYSWM_MIR      SysWMType = C.SDL_SYSWM_MIR
	SYSWM_WINRT    SysWMType = C.SDL_SYSWM_WINRT
	SYSWM_ANDROID  SysWMType = C.SDL_SYSWM_ANDROID
)
