package xed

/*
#include <xed-interface.h>
*/
import "C"

const (
	ISA_SET_INVALID               ISASet = C.XED_ISA_SET_INVALID
	ISA_SET_3DNOW                 ISASet = C.XED_ISA_SET_3DNOW
	ISA_SET_ADOX_ADCX             ISASet = C.XED_ISA_SET_ADOX_ADCX
	ISA_SET_AES                   ISASet = C.XED_ISA_SET_AES
	ISA_SET_AMD                   ISASet = C.XED_ISA_SET_AMD
	ISA_SET_AVX                   ISASet = C.XED_ISA_SET_AVX
	ISA_SET_AVX2                  ISASet = C.XED_ISA_SET_AVX2
	ISA_SET_AVX2GATHER            ISASet = C.XED_ISA_SET_AVX2GATHER
	ISA_SET_AVX512BW_128          ISASet = C.XED_ISA_SET_AVX512BW_128
	ISA_SET_AVX512BW_128N         ISASet = C.XED_ISA_SET_AVX512BW_128N
	ISA_SET_AVX512BW_256          ISASet = C.XED_ISA_SET_AVX512BW_256
	ISA_SET_AVX512BW_512          ISASet = C.XED_ISA_SET_AVX512BW_512
	ISA_SET_AVX512BW_KOP          ISASet = C.XED_ISA_SET_AVX512BW_KOP
	ISA_SET_AVX512CD_128          ISASet = C.XED_ISA_SET_AVX512CD_128
	ISA_SET_AVX512CD_256          ISASet = C.XED_ISA_SET_AVX512CD_256
	ISA_SET_AVX512CD_512          ISASet = C.XED_ISA_SET_AVX512CD_512
	ISA_SET_AVX512DQ_128          ISASet = C.XED_ISA_SET_AVX512DQ_128
	ISA_SET_AVX512DQ_128N         ISASet = C.XED_ISA_SET_AVX512DQ_128N
	ISA_SET_AVX512DQ_256          ISASet = C.XED_ISA_SET_AVX512DQ_256
	ISA_SET_AVX512DQ_512          ISASet = C.XED_ISA_SET_AVX512DQ_512
	ISA_SET_AVX512DQ_KOP          ISASet = C.XED_ISA_SET_AVX512DQ_KOP
	ISA_SET_AVX512DQ_SCALAR       ISASet = C.XED_ISA_SET_AVX512DQ_SCALAR
	ISA_SET_AVX512ER_512          ISASet = C.XED_ISA_SET_AVX512ER_512
	ISA_SET_AVX512ER_SCALAR       ISASet = C.XED_ISA_SET_AVX512ER_SCALAR
	ISA_SET_AVX512F_128           ISASet = C.XED_ISA_SET_AVX512F_128
	ISA_SET_AVX512F_128N          ISASet = C.XED_ISA_SET_AVX512F_128N
	ISA_SET_AVX512F_256           ISASet = C.XED_ISA_SET_AVX512F_256
	ISA_SET_AVX512F_512           ISASet = C.XED_ISA_SET_AVX512F_512
	ISA_SET_AVX512F_KOP           ISASet = C.XED_ISA_SET_AVX512F_KOP
	ISA_SET_AVX512F_SCALAR        ISASet = C.XED_ISA_SET_AVX512F_SCALAR
	ISA_SET_AVX512PF_512          ISASet = C.XED_ISA_SET_AVX512PF_512
	ISA_SET_AVX512_4FMAPS_512     ISASet = C.XED_ISA_SET_AVX512_4FMAPS_512
	ISA_SET_AVX512_4FMAPS_SCALAR  ISASet = C.XED_ISA_SET_AVX512_4FMAPS_SCALAR
	ISA_SET_AVX512_4VNNIW_512     ISASet = C.XED_ISA_SET_AVX512_4VNNIW_512
	ISA_SET_AVX512_BITALG_128     ISASet = C.XED_ISA_SET_AVX512_BITALG_128
	ISA_SET_AVX512_BITALG_256     ISASet = C.XED_ISA_SET_AVX512_BITALG_256
	ISA_SET_AVX512_BITALG_512     ISASet = C.XED_ISA_SET_AVX512_BITALG_512
	ISA_SET_AVX512_GFNI_128       ISASet = C.XED_ISA_SET_AVX512_GFNI_128
	ISA_SET_AVX512_GFNI_256       ISASet = C.XED_ISA_SET_AVX512_GFNI_256
	ISA_SET_AVX512_GFNI_512       ISASet = C.XED_ISA_SET_AVX512_GFNI_512
	ISA_SET_AVX512_IFMA_128       ISASet = C.XED_ISA_SET_AVX512_IFMA_128
	ISA_SET_AVX512_IFMA_256       ISASet = C.XED_ISA_SET_AVX512_IFMA_256
	ISA_SET_AVX512_IFMA_512       ISASet = C.XED_ISA_SET_AVX512_IFMA_512
	ISA_SET_AVX512_VAES_128       ISASet = C.XED_ISA_SET_AVX512_VAES_128
	ISA_SET_AVX512_VAES_256       ISASet = C.XED_ISA_SET_AVX512_VAES_256
	ISA_SET_AVX512_VAES_512       ISASet = C.XED_ISA_SET_AVX512_VAES_512
	ISA_SET_AVX512_VBMI2_128      ISASet = C.XED_ISA_SET_AVX512_VBMI2_128
	ISA_SET_AVX512_VBMI2_256      ISASet = C.XED_ISA_SET_AVX512_VBMI2_256
	ISA_SET_AVX512_VBMI2_512      ISASet = C.XED_ISA_SET_AVX512_VBMI2_512
	ISA_SET_AVX512_VBMI_128       ISASet = C.XED_ISA_SET_AVX512_VBMI_128
	ISA_SET_AVX512_VBMI_256       ISASet = C.XED_ISA_SET_AVX512_VBMI_256
	ISA_SET_AVX512_VBMI_512       ISASet = C.XED_ISA_SET_AVX512_VBMI_512
	ISA_SET_AVX512_VNNI_128       ISASet = C.XED_ISA_SET_AVX512_VNNI_128
	ISA_SET_AVX512_VNNI_256       ISASet = C.XED_ISA_SET_AVX512_VNNI_256
	ISA_SET_AVX512_VNNI_512       ISASet = C.XED_ISA_SET_AVX512_VNNI_512
	ISA_SET_AVX512_VPCLMULQDQ_128 ISASet = C.XED_ISA_SET_AVX512_VPCLMULQDQ_128
	ISA_SET_AVX512_VPCLMULQDQ_256 ISASet = C.XED_ISA_SET_AVX512_VPCLMULQDQ_256
	ISA_SET_AVX512_VPCLMULQDQ_512 ISASet = C.XED_ISA_SET_AVX512_VPCLMULQDQ_512
	ISA_SET_AVX512_VPOPCNTDQ_128  ISASet = C.XED_ISA_SET_AVX512_VPOPCNTDQ_128
	ISA_SET_AVX512_VPOPCNTDQ_256  ISASet = C.XED_ISA_SET_AVX512_VPOPCNTDQ_256
	ISA_SET_AVX512_VPOPCNTDQ_512  ISASet = C.XED_ISA_SET_AVX512_VPOPCNTDQ_512
	ISA_SET_AVXAES                ISASet = C.XED_ISA_SET_AVXAES
	ISA_SET_AVX_GFNI              ISASet = C.XED_ISA_SET_AVX_GFNI
	ISA_SET_BMI1                  ISASet = C.XED_ISA_SET_BMI1
	ISA_SET_BMI2                  ISASet = C.XED_ISA_SET_BMI2
	ISA_SET_CET                   ISASet = C.XED_ISA_SET_CET
	ISA_SET_CLDEMOTE              ISASet = C.XED_ISA_SET_CLDEMOTE
	ISA_SET_CLFLUSHOPT            ISASet = C.XED_ISA_SET_CLFLUSHOPT
	ISA_SET_CLFSH                 ISASet = C.XED_ISA_SET_CLFSH
	ISA_SET_CLWB                  ISASet = C.XED_ISA_SET_CLWB
	ISA_SET_CLZERO                ISASet = C.XED_ISA_SET_CLZERO
	ISA_SET_CMOV                  ISASet = C.XED_ISA_SET_CMOV
	ISA_SET_CMPXCHG16B            ISASet = C.XED_ISA_SET_CMPXCHG16B
	ISA_SET_F16C                  ISASet = C.XED_ISA_SET_F16C
	ISA_SET_FAT_NOP               ISASet = C.XED_ISA_SET_FAT_NOP
	ISA_SET_FCMOV                 ISASet = C.XED_ISA_SET_FCMOV
	ISA_SET_FMA                   ISASet = C.XED_ISA_SET_FMA
	ISA_SET_FMA4                  ISASet = C.XED_ISA_SET_FMA4
	ISA_SET_FXSAVE                ISASet = C.XED_ISA_SET_FXSAVE
	ISA_SET_FXSAVE64              ISASet = C.XED_ISA_SET_FXSAVE64
	ISA_SET_GFNI                  ISASet = C.XED_ISA_SET_GFNI
	ISA_SET_I186                  ISASet = C.XED_ISA_SET_I186
	ISA_SET_I286PROTECTED         ISASet = C.XED_ISA_SET_I286PROTECTED
	ISA_SET_I286REAL              ISASet = C.XED_ISA_SET_I286REAL
	ISA_SET_I386                  ISASet = C.XED_ISA_SET_I386
	ISA_SET_I486                  ISASet = C.XED_ISA_SET_I486
	ISA_SET_I486REAL              ISASet = C.XED_ISA_SET_I486REAL
	ISA_SET_I86                   ISASet = C.XED_ISA_SET_I86
	ISA_SET_INVPCID               ISASet = C.XED_ISA_SET_INVPCID
	ISA_SET_LAHF                  ISASet = C.XED_ISA_SET_LAHF
	ISA_SET_LONGMODE              ISASet = C.XED_ISA_SET_LONGMODE
	ISA_SET_LZCNT                 ISASet = C.XED_ISA_SET_LZCNT
	ISA_SET_MONITOR               ISASet = C.XED_ISA_SET_MONITOR
	ISA_SET_MONITORX              ISASet = C.XED_ISA_SET_MONITORX
	ISA_SET_MOVBE                 ISASet = C.XED_ISA_SET_MOVBE
	ISA_SET_MOVDIR                ISASet = C.XED_ISA_SET_MOVDIR
	ISA_SET_MPX                   ISASet = C.XED_ISA_SET_MPX
	ISA_SET_PAUSE                 ISASet = C.XED_ISA_SET_PAUSE
	ISA_SET_PCLMULQDQ             ISASet = C.XED_ISA_SET_PCLMULQDQ
	ISA_SET_PCONFIG               ISASet = C.XED_ISA_SET_PCONFIG
	ISA_SET_PENTIUMMMX            ISASet = C.XED_ISA_SET_PENTIUMMMX
	ISA_SET_PENTIUMREAL           ISASet = C.XED_ISA_SET_PENTIUMREAL
	ISA_SET_PKU                   ISASet = C.XED_ISA_SET_PKU
	ISA_SET_POPCNT                ISASet = C.XED_ISA_SET_POPCNT
	ISA_SET_PPRO                  ISASet = C.XED_ISA_SET_PPRO
	ISA_SET_PREFETCHW             ISASet = C.XED_ISA_SET_PREFETCHW
	ISA_SET_PREFETCHWT1           ISASet = C.XED_ISA_SET_PREFETCHWT1
	ISA_SET_PREFETCH_NOP          ISASet = C.XED_ISA_SET_PREFETCH_NOP
	ISA_SET_PT                    ISASet = C.XED_ISA_SET_PT
	ISA_SET_RDPID                 ISASet = C.XED_ISA_SET_RDPID
	ISA_SET_RDPMC                 ISASet = C.XED_ISA_SET_RDPMC
	ISA_SET_RDRAND                ISASet = C.XED_ISA_SET_RDRAND
	ISA_SET_RDSEED                ISASet = C.XED_ISA_SET_RDSEED
	ISA_SET_RDTSCP                ISASet = C.XED_ISA_SET_RDTSCP
	ISA_SET_RDWRFSGS              ISASet = C.XED_ISA_SET_RDWRFSGS
	ISA_SET_RTM                   ISASet = C.XED_ISA_SET_RTM
	ISA_SET_SGX                   ISASet = C.XED_ISA_SET_SGX
	ISA_SET_SGX_ENCLV             ISASet = C.XED_ISA_SET_SGX_ENCLV
	ISA_SET_SHA                   ISASet = C.XED_ISA_SET_SHA
	ISA_SET_SMAP                  ISASet = C.XED_ISA_SET_SMAP
	ISA_SET_SMX                   ISASet = C.XED_ISA_SET_SMX
	ISA_SET_SSE                   ISASet = C.XED_ISA_SET_SSE
	ISA_SET_SSE2                  ISASet = C.XED_ISA_SET_SSE2
	ISA_SET_SSE2MMX               ISASet = C.XED_ISA_SET_SSE2MMX
	ISA_SET_SSE3                  ISASet = C.XED_ISA_SET_SSE3
	ISA_SET_SSE3X87               ISASet = C.XED_ISA_SET_SSE3X87
	ISA_SET_SSE4                  ISASet = C.XED_ISA_SET_SSE4
	ISA_SET_SSE42                 ISASet = C.XED_ISA_SET_SSE42
	ISA_SET_SSE4A                 ISASet = C.XED_ISA_SET_SSE4A
	ISA_SET_SSEMXCSR              ISASet = C.XED_ISA_SET_SSEMXCSR
	ISA_SET_SSE_PREFETCH          ISASet = C.XED_ISA_SET_SSE_PREFETCH
	ISA_SET_SSSE3                 ISASet = C.XED_ISA_SET_SSSE3
	ISA_SET_SSSE3MMX              ISASet = C.XED_ISA_SET_SSSE3MMX
	ISA_SET_SVM                   ISASet = C.XED_ISA_SET_SVM
	ISA_SET_TBM                   ISASet = C.XED_ISA_SET_TBM
	ISA_SET_VAES                  ISASet = C.XED_ISA_SET_VAES
	ISA_SET_VMFUNC                ISASet = C.XED_ISA_SET_VMFUNC
	ISA_SET_VPCLMULQDQ            ISASet = C.XED_ISA_SET_VPCLMULQDQ
	ISA_SET_VTX                   ISASet = C.XED_ISA_SET_VTX
	ISA_SET_WAITPKG               ISASet = C.XED_ISA_SET_WAITPKG
	ISA_SET_WBNOINVD              ISASet = C.XED_ISA_SET_WBNOINVD
	ISA_SET_X87                   ISASet = C.XED_ISA_SET_X87
	ISA_SET_XOP                   ISASet = C.XED_ISA_SET_XOP
	ISA_SET_XSAVE                 ISASet = C.XED_ISA_SET_XSAVE
	ISA_SET_XSAVEC                ISASet = C.XED_ISA_SET_XSAVEC
	ISA_SET_XSAVEOPT              ISASet = C.XED_ISA_SET_XSAVEOPT
	ISA_SET_XSAVES                ISASet = C.XED_ISA_SET_XSAVES
	ISA_SET_LAST                  ISASet = C.XED_ISA_SET_LAST
)

func (c ISASet) String() string {
	return C.GoString(C.xed_isa_set_enum_t2str(C.xed_isa_set_enum_t(c)))
}

func (c ISASet) CPUIDBit(i uint) CPUIDBit {
	return CPUIDBit(C.xed_get_cpuid_bit_for_isa_set(C.xed_isa_set_enum_t(c), C.xed_uint_t(i)))
}