package btatt

// Attribute Protocol Opcodes
const (
	OP_ERROR              = 0x01
	OP_MTU_REQ            = 0x02
	OP_MTU_RESP           = 0x03
	OP_FIND_INFO_REQ      = 0x04
	OP_FIND_INFO_RESP     = 0x05
	OP_FIND_BY_TYPE_REQ   = 0x06
	OP_FIND_BY_TYPE_RESP  = 0x07
	OP_READ_BY_TYPE_REQ   = 0x08
	OP_READ_BY_TYPE_RESP  = 0x09
	OP_READ_REQ           = 0x0A
	OP_READ_RESP          = 0x0B
	OP_READ_BLOB_REQ      = 0x0C
	OP_READ_BLOB_RESP     = 0x0D
	OP_READ_MULTI_REQ     = 0x0E
	OP_READ_MULTI_RESP    = 0x0F
	OP_READ_BY_GROUP_REQ  = 0x10
	OP_READ_BY_GROUP_RESP = 0x11
	OP_WRITE_REQ          = 0x12
	OP_WRITE_RESP         = 0x13
	OP_WRITE_CMD          = 0x52
	OP_PREP_WRITE_REQ     = 0x16
	OP_PREP_WRITE_RESP    = 0x17
	OP_EXEC_WRITE_REQ     = 0x18
	OP_EXEC_WRITE_RESP    = 0x19
	OP_HANDLE_NOTIFY      = 0x1B
	OP_HANDLE_IND         = 0x1D
	OP_HANDLE_CNF         = 0x1E
	OP_SIGNED_WRITE_CMD   = 0xD2
)

// Error codes for Error response PDU
const (
	ERROR_INVALID_HANDLE       = 0x01
	ERROR_READ_NOT_PERM        = 0x02
	ERROR_WRITE_NOT_PERM       = 0x03
	ERROR_INVALID_PDU          = 0x04
	ERROR_AUTHENTICATION       = 0x05
	ERROR_REQ_NOT_SUPP         = 0x06
	ERROR_INVALID_OFFSET       = 0x07
	ERROR_AUTHORIZATION        = 0x08
	ERROR_PREP_QUEUE_FULL      = 0x09
	ERROR_ATTR_NOT_FOUND       = 0x0A
	ERROR_ATTR_NOT_LONG        = 0x0B
	ERROR_INSUFF_ENCR_KEY_SIZE = 0x0C
	ERROR_INVAL_ATTR_VALUE_LEN = 0x0D
	ERROR_UNLIKELY             = 0x0E
	ERROR_INSUFF_ENC           = 0x0F
	ERROR_UNSUPP_GRP_TYPE      = 0x10
	ERROR_INSUFF_RESOURCES     = 0x11
)

// Application error
const (
	ERROR_IO      = 0x80
	ERROR_TIMEOUT = 0x81
	ERROR_ABORTED = 0x82
)

// Characteristic Property bit field
const (
	CHAR_PROPER_BROADCAST          = 0x01
	CHAR_PROPER_READ               = 0x02
	CHAR_PROPER_WRITE_WITHOUT_RESP = 0x04
	CHAR_PROPER_WRITE              = 0x08
	CHAR_PROPER_NOTIFY             = 0x10
	CHAR_PROPER_INDICATE           = 0x20
	CHAR_PROPER_AUTH               = 0x40
	CHAR_PROPER_EXT_PROPER         = 0x80

	MAX_VALUE_LEN     = 512
	DEFAULT_L2CAP_MTU = 48
	DEFAULT_LE_MTU    = 23
)

const (
	CID = 4
	PSM = 31
)

const (
	CANCEL_ALL_PREP_WRITES = 0x00
	WRITE_ALL_PREP_WRITES  = 0x01
)

const (
	FIND_INFO_RESP_FMT_16BIT  = 0x01
	FIND_INFO_RESP_FMT_128BIT = 0x02
)

const (
	PERM_READ          = 0x01
	PERM_WRITE         = 0x02
	PERM_READ_ENCRYPT  = 0x04
	PERM_WRITE_ENCRYPT = 0x08
	PERM_ENCRYPT       = PERM_READ_ENCRYPT | PERM_WRITE_ENCRYPT
	PERM_READ_AUTHEN   = 0x10
	PERM_WRITE_AUTHEN  = 0x20
	PERM_AUTHEN        = PERM_READ_AUTHEN | PERM_WRITE_AUTHEN
	PERM_AUTHOR        = 0x40
	PERM_NONE          = 0x80
	PERM_READ_SECURE   = 0x100
	PERM_WRITE_SECURE  = 0x200
	PERM_SECURE        = PERM_READ_SECURE | PERM_WRITE_SECURE
)
